
# 1. Configuración de Base de Datos (JDBC)
spring.application.name=udam2

spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.profiles.active=local

spring.datasource.hikari.pool-name=udam2Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# 2. Configuración de Ficheros CSV
csv.ruta.base=src/main/resources/ficheros/data/

# Nombres de archivos por entidad
csv.patient.file-name=patients.csv
csv.doctor.file-name=doctors.csv
csv.appointment.file-name=appointments.csv

# Parámetros comunes de CSV
csv.parser.delimiter=,
csv.parser.skip-headers=true

# 3. Propiedad de Alternancia (CLAVE)
# Valores posibles: "jdbc" (usa la DB) o "csv" (usa los ficheros)
app.data.source=jdbc